apiVersion: apps/v1
kind: Deployment
metadata:
  name: q5-app-prod
  namespace: production
spec:
  selector:
    matchLabels:
      app: q5-app
  template:
    metadata:
      labels:
        app: q5-app
    spec:
      containers:
      - name: backend
        image: q5-image:1.0
        imagePullPolicy: Never
        env:
        - name: APP_ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: q5-service-prod
  namespace: production
spec:
  type: LoadBalancer
  selector:
    app: q5-app
  ports:
    - port: 8000 # Prod environment port
      targetPort: 5000
