# Combined K8s file for Frontend and Backend Migration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: q3-backend
spec:
  selector:
    matchLabels:
      app: q3-backend
  template:
    metadata:
      labels:
        app: q3-backend
    spec:
      containers:
      - name: backend
        image: q3-backend:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: q3-backend-service
spec:
  type: LoadBalancer
  selector:
    app: q3-backend
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: q3-frontend
spec:
  selector:
    matchLabels:
      app: q3-frontend
  template:
    metadata:
      labels:
        app: q3-frontend
    spec:
      containers:
      - name: frontend
        image: q3-frontend:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: q3-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: q3-frontend
  ports:
    - port: 3000
      targetPort: 3000
